<?php

namespace AppBundle\Repository;

/**
 * PublicationCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
