<?php

namespace AppBundle\Repository;

/**
 * RefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefTagRepository extends \Doctrine\ORM\EntityRepository
{
}
