<?php

namespace AppBundle\Repository;

/**
 * SharedBibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedRefRepository extends \Doctrine\ORM\EntityRepository
{
}
